name: Auto Tag on Version Change

on:
  push:
    branches:
      - main
    paths:
      - 'version.mk'

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史，用于比较变更
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract version from version.mk
      id: extract_version
      run: |
        # 从version.mk文件中提取QMODEM_VERSION
        version=$(grep "^QMODEM_VERSION" version.mk | sed 's/QMODEM_VERSION:=//' | xargs)
        echo "Current QMODEM_VERSION: $version"
        echo "version=$version" >> $GITHUB_OUTPUT
        
        # 检查version是否为空
        if [ -z "$version" ]; then
          echo "Error: Could not extract version from version.mk"
          exit 1
        fi
        
        # 生成tag名称
        tag_name="v$version"
        echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
        echo "Generated tag name: $tag_name"
    
    - name: Check if tag already exists
      id: check_tag
      run: |
        tag_name="${{ steps.extract_version.outputs.tag_name }}"
        
        # 检查tag是否已经存在
        if git tag -l | grep -q "^${tag_name}$"; then
          echo "Tag $tag_name already exists, skipping tag creation"
          echo "tag_exists=true" >> $GITHUB_OUTPUT
        else
          echo "Tag $tag_name does not exist, will create it"
          echo "tag_exists=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Create and push tag
      if: steps.check_tag.outputs.tag_exists == 'false'
      run: |
        tag_name="${{ steps.extract_version.outputs.tag_name }}"
        version="${{ steps.extract_version.outputs.version }}"
        
        # 配置git用户信息
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # 创建带注释的tag
        git tag -a "$tag_name" -m "Release version $version - Auto-generated tag when QMODEM_VERSION was updated to $version"
        
        # 推送tag到远程仓库
        git push origin "$tag_name"
        
        echo "✅ Successfully created and pushed tag: $tag_name"
